name: Deploy to Heroku

on:
  push:
    branches:
      - api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Heroku CLI
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: projetp7api

      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/projetp7api.git
          git push heroku api:main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
