name: Deploy to Heroku

on:
  push:
    branches:
      - api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Heroku CLI
        uses: actions/heroku@v4
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "projetp7api"

      - name: Deploy to Heroku
        run: git push heroku HEAD:main
